### ISSUE TITLE
Crush on 7.0.1 ASM 0.8.9 

### ISSUE THREAD

**Issue by sillyas2010** [XorTroll/emuiibo#17] opened 2019-05-11 07:14 UTC
After placing v0.2 emuiibo files from 'archive'/atmosphere/titles/.... to 'sdcard'/atmosphere/titles/... and reboot - on startup crashes to atmosphere error screen, fixes after removing emuiibo folder from 'sdcard'/atmosphere/titles/...

**Comment by sillyas2010** [comment] 2019-05-11 07:17
P.S using Kosmos v12.1.2

**Comment by sillyas2010** [comment] 2019-05-11 07:31
Now tried downgrade to v0.1 emuiibo , almost same situation but crashes to atmosphere error screen not after startup, but after going to hb-menu(R+album)

**Comment by deurk** [comment] 2019-05-11 09:05
I am running it without Kosmos on Atmosphere 0.8.9 and Horizon 7.0.1 without such an issue.

**Comment by sakatsuku** [comment] 2019-05-11 10:50
the same boot crush on 8.0.1  Atmosphere 0.8.9
v0.2 does not support  Atmosphere?

**Comment by deurk** [comment] 2019-05-11 11:53
I am running ATM and Emuiibo 0.2

**Comment by ruvaldak** [comment] 2019-05-12 01:35
It seems that Kosmos does not support 0.2 yet. Crashes on my system running kosmos 12.1.2.

**Comment by deurk** [comment] 2019-05-14 14:39
Not an emuiibo issue afaik. We could close this.

**Comment by ruvaldak** [comment] 2019-05-19 08:11
Just removed Kosmos, replaced it with regular atmosphere, and switched to using Fusee Primary. Emuiibo still crashes. Going to clean SD card of everything and try again, but I don't think the problem is exclusive to kosmos. I'm on 8.0.1, btw.

**Comment by deurk** [comment] 2019-05-19 10:16
Really weird.

I have updated my setup to 8.0.1 after running successfully Emuiibo 0.2 with 7.0.1 and it crashed. Cleaned up my SD card and restart it from scratch, made sure everything was working in 8.0.1 with sigpatches before adding Emuiibo and had no issue adding it in afterwards.

**Comment by ruvaldak** [comment] 2019-05-19 10:35
maybe I'll have to backup my sdcard or something and format it, might be something laying around somewhere causing problems.

**Comment by deurk** [comment] 2019-05-19 11:25
Make a backup, format it and only install Atmosphere 0.8.9 and sigpatches. Make sure it works OK. Then add Emuiibo and see how it goes. Let us know.

**Comment by ruvaldak** [comment] 2019-05-23 06:53
Apologies for the long wait, I got distracted and ended up forgetting to do this. Anyways, backed up my SD card, dropped a clean copy of atmosphere + sigpatches on there, dropped emuiibo in there plus some amiibo bins, and still crash on boot. I wonder if it has to do with the fact my switch was updated with Choi, so it has I think too many fuses, and also has autorcm? [Here's](https://i.imgur.com/gIIbmqd.jpg) a picture of the error screen, as well, if it helps any

**Comment by lookye** [comment] 2019-05-23 06:59
@ruvaldak 
I had the same setup as you for testing purposes and it works fine.
Have you checked the archive bit for the atmosphere/titles/xxxxx352 folder? Is the content in the correct place inside that folder?

**Comment by ruvaldak** [comment] 2019-05-23 07:02
Should be. folder structure is drag-n-dropped from releases zip, so:

atmosphere
-titles
--xxxxx352
---flags
----boot2.flag
---exefs.nsp

Is there anything extra I needed to do? Maybe I'm just dumb lol

**Comment by deurk** [comment] 2019-05-23 07:24
I have the same setup :

- FW 8.0.1 upgraded with ChoiNX
- Atmosphere 0.8.9
- Sigpatches
- Emuiibo 0.2
- SD card 256G formatted in FAT32
- Booting with fusee-primary.bin
- Folder structure as you mentioned (same as release)

It works just fine :|
Wonder what could create your issue.

**Comment by lookye** [comment] 2019-05-23 07:26
@ruvaldak Please check the Archive Bit. If youre unsure how to do that, boot into hekate -> tools
and let it fix everything except Nintendo folder.

**Comment by ruvaldak** [comment] 2019-05-23 07:37
@lookye same issue still. crashes instantly after the switch logo fades away. Error code 2168-0002 (0x4a8)
At first after fixing archive bit rather than crashing and staying on the error screen it'd crash then quickly throw some fatal error message, then reboot, but after removing the files from the sdcard and replacing them that went away, and fixing archive bit again didn't recreate the first issue so may have been a one time thing.

**Comment by lookye** [comment] 2019-05-23 07:41
<img width="193" alt="Bildschirmfoto 2019-05-23 um 09 39 42" src="https://user-images.githubusercontent.com/45557556/58234424-c64ead00-7d3e-11e9-8e46-354414b6d645.png">
Does it look like this on your SD Card? I saw you wrote something about a .bak file. The correct file layout is in the release download.

**Comment by ruvaldak** [comment] 2019-05-23 07:43
Lol as I am on windows a single screenshot wouldn't quite work but yes, that is how my sd card looks. I was just renaming stuff to test things, but at this moment that is how it looks. No extra files or anything.

**Comment by lookye** [comment] 2019-05-23 07:52
The sigpatches should not interfere.
Are the amiibos correct?
- Not longer than 12chars long
- Directly in the emuiibo folder (emuiibo will copy them in their on folder on boot)

**Comment by ruvaldak** [comment] 2019-05-23 08:02
Well, I had several in there that did not follow that rule, however I cut it down to just 1 amiibo that worked on 0.1 (toon link) and renamed it linkt.bin, and it still crashed. I get a miis folder, but linkt.bin is still in the root of the emuiibo folder.

**Comment by TheRadziu** [comment] 2019-05-23 17:44
+1

can confirm same happens on latest switch FW + latest atmosphere (0.8.10) although I heard it might be because i have 'too many modules' at this point (ftpd + ldm_mtm)

**Comment by ruvaldak** [comment] 2019-05-23 17:56
Kosmos is getting an update soon™ with updated emuiibo, we'll see if that still crashes.

**Comment by tumGER** [comment] 2019-05-23 19:13
Note: We haven't changed anything so it's still the 0.2 release

**Comment by james-d-elliott** [comment] 2019-05-27 23:04
https://github.com/AtlasNX/Kosmos/issues/222 relates to this. Has @ruvaldak  tried disabling ldn_mitm if it's enabled?

**Comment by ruvaldak** [comment] 2019-05-27 23:52
Does ldn_mitm come by default on atmosphere? Because it still crashed with the 8.10 atmosphere release zip + this and sigpatches, and nothing extra downloaded.

**Comment by JonJaded** [comment] 2019-05-28 01:24
> [AtlasNX/Kosmos#222](https://github.com/AtlasNX/Kosmos/issues/222) relates to this. Has @ruvaldak tried disabling/removing ldn_mitm if it's enabled?

I can 100% assure you it's ldn_mitm. This same issue occurred when you were able to activate sys-netcheat and sys-ftpd at the same time.

DIdn't know anyone was struggling with this. [I actually mentioned it on gba-temp here a while back.](https://gbatemp.net/threads/emuiibo-mitming-nfp-services-for-amiibo-emulation.536210/page-15#post-8630742) I was just too lazy to report it.


> Does ldn_mitm come by default on atmosphere? Because it still crashed with the 8.10 atmosphere release zip + this and sigpatches, and nothing extra downloaded.

Yes it does. You can by pass that by adding ldn_mitm via ftp.

**Comment by ruvaldak** [comment] 2019-05-28 06:46
> > [AtlasNX/Kosmos#222](https://github.com/AtlasNX/Kosmos/issues/222) relates to this. Has @ruvaldak tried disabling/removing ldn_mitm if it's enabled?
> 
> I can 100% assure you it's ldn_mitm. This same issue occurred when you were able to activate sys-netcheat and sys-ftpd at the same time.
> 
> DIdn't know anyone was struggling with this. [I actually mentioned it on gba-temp here a while back.](https://gbatemp.net/threads/emuiibo-mitming-nfp-services-for-amiibo-emulation.536210/page-15#post-8630742) I was just too lazy to report it.
> 
> > Does ldn_mitm come by default on atmosphere? Because it still crashed with the 8.10 atmosphere release zip + this and sigpatches, and nothing extra downloaded.
> 
> Yes it does. You can bypass that by adding ldn_mitm via ftp. Not the most ideal but works.

It was not ldn_mitm. Worth noting in your gba-temp you mention a 2003-0008 error. This, or mine, is a 2168-0002 error.

**Comment by ruvaldak** [comment] 2019-05-28 07:04
Alright boys, I found the cause. If you have any miis with special characters in their names, remove them. These are accented letters, possibly punctuation like ! or ?, and other things. I guess just leave it to alphanumeric. [Also reported](https://gbatemp.net/threads/emuiibo-mitming-nfp-services-for-amiibo-emulation.536210/page-17#post-8638781) that too many miis can also cause this crash.

**Comment by chrisf95** [comment] 2019-06-15 00:38
> Alright boys, I found the cause. If you have any miis with special characters in their names, remove them. These are accented letters, possibly punctuation like ! or ?, and other things. I guess just leave it to alphanumeric. [Also reported](https://gbatemp.net/threads/emuiibo-mitming-nfp-services-for-amiibo-emulation.536210/page-17#post-8638781) that too many miis can also cause this crash.

Hi, I have the crash on boot with fw 8.0.1 and atmosphere 0.8.10, but I don't have any .bin... I have the crash when I activate the sys module in kosmos tool

**Comment by XorTroll** [comment] 2019-07-09 19:41
Too many sysmodules = crash
Just toggle a few, those you really will use.

**Closed by XorTroll** 2019-07-09 19:41 UTC
