### ISSUE TITLE
Does not work correctly with several games:

### ISSUE THREAD

**Issue by PeterMaxu** [XorTroll/emuiibo#23] opened 2019-06-03 17:27 UTC
Does not work correctly with several games:

Splatoon 2
Conga Master Party
Megaman Legacy Collection

**Comment by XorTroll** [comment] 2020-04-09 17:50
Considering how old the issue is I'm closing it, check if the next version works fine with this amiibo (I've personally tested Splatoon 2 and it does work fine)

**Closed by XorTroll** 2020-04-09 17:50 UTC
