### ISSUE TITLE
Emutool: selecting Amiibos with same name cause error System.InvalidOperationException

### ISSUE THREAD

**Issue by enricojacko** [XorTroll/emuiibo#68] opened 2020-02-21 17:22 UTC
Emutool on PC, folder in root directory C:\Emuiibo\Release (no special permissions folder).
If there are more than 1 Amiibos with same name inside a group (example: Animal Crossing), selecting one of them cause immediately error System.InvalidOperationException: Sequence contains more than one element

Full text (italian Windows version:)

Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.InvalidOperationException: La sequenza contiene più elementi
   in System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   in emutool.MainForm.comboBox2_SelectedIndexChanged(Object sender, EventArgs e) in E:\Nintendo\Switch\Proyectos\emuiibo\emutool\emutool\MainForm.cs:riga 60
   in System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   in System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   in System.Windows.Forms.ComboBox.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4121.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
emutool
    Versione assembly: 0.4.0.0
    Versione Win32: 0.4.0.0
    Base di codice: file:///C:/Emuiibo/Release/emutool.exe
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4121.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4001.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.4121.0 built by: NET48REL1LAST_C
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Versione assembly: 12.0.0.0
    Versione Win32: 12.0.2.23222
    Base di codice: file:///C:/Emuiibo/Release/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Core.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Core.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.8.3752.0 built by: NET48REL1
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by dyerseve** [comment] 2020-03-21 01:28
This is probably a dupe of issue #54 
The other issue has some code to eliminate the dupe, but the only problem I see with that is the dupes are not technically dupes, if you query Digby for example
https://www.amiiboapi.com/api/amiibo/?character=digby
The images show that these are unique amiibos but Nintendo named them the same. One is a figure and the other two are cards. It might be easy to just append "figure" and "card" but the dupe card still poses a problem, perhaps count them, "Card 1", "Card 2"
Due to the bug though we can't create any of the dupes unless you just do it manually which isn't that bad really.

**Comment by MaymonAdir** [comment] 2020-03-23 20:36
Try using Amiigo, it's an Amiibos maker and Emuiibo for switch. Works for me 😊

**Comment by mrbob312** [comment] 2020-03-24 19:43
This is fixed in my fork (I already created a pull request)

**Comment by XorTroll** [comment] 2020-04-09 17:45
Fixed for the next version

**Closed by XorTroll** 2020-04-09 17:45 UTC
