### ISSUE TITLE
Inkling amiibos not being differed correctly

### ISSUE THREAD

**Issue by M4th3wIsntHere** [XorTroll/emuiibo#204] opened 2022-02-27 18:27 UTC
i guess someone has reported this already but i am gonna do so again, basically, splatoon has 6 variations for the  inkling amiibos, blue boy, neon green boy, purple boy, orange girl, green girl and neon pink girl.
starting this, purple boy shows up as blue boy, that doesnt really affect anything as they give the same things in-game BUT the neon green boy shows up also as blue boy, and it shouldnt as the neon green boy is a splatoon 2 exclusive amiibo and does give a different reward, so i cant claim it;
same happening with inkling girls, using the green one shows up the orange one and using the neon pink one that is the splatoon 2 exclusive that should give you different things also shows as the orange one, and this is a request for the devs to take a look at it, inkling squids amiibos are differed correctly, but that doesnt happen with the inkling amiibos

**Comment by lookye** [comment] 2022-02-27 19:01
Duplicate of #148

**Comment by M4th3wIsntHere** [comment] 2022-02-27 20:53
and #148 is about 1 year old

**Comment by lookye** [comment] 2022-02-27 21:00
And it hasnt changed yet. A fix will come in a future release.

**Comment by impeeza** [comment] 2022-02-27 21:01
Yes. You can comment on it

**Comment by lookye** [comment] 2023-05-06 13:46
This is resolved.

**Closed by lookye** 2023-05-06 13:46 UTC
