### ISSUE TITLE
Monster Hunter Rise not recognizing Amiibo's correctly 

### ISSUE THREAD

**Issue by Brandonspikes** [XorTroll/emuiibo#161] opened 2021-03-27 01:26 UTC
Tried in every other game, latest version of emuiibo , Rise sees every amiibo as the same type.

I've tried the Magnamalo, Palico, and Palamute virtual amiibo's and was unable to redeem the rewards.

**Comment by nebula-gh** [comment] 2021-03-27 05:45
me too

**Comment by RQV14** [comment] 2021-03-27 08:40
maybe because the game update is 18.1 and emuiibo only support for 18.0

**Comment by impeeza** [comment] 2021-03-27 09:27
The changes between atmosphère 1.8.0 & 1.8.1 are minor and none seems related to any sys modules but dns one

**Comment by NumberXer0** [comment] 2021-03-27 13:44
Can also confirm. The 3 amiibos are recognized, but as generic ones. They do not provide the one time armor bonuses as they should.

**Comment by lookye** [comment] 2021-03-28 11:45
This is known and will be looked into.

**Comment by jacobvibert97** [comment] 2021-04-24 14:29
Any updates on this issue? Since the last update didn't seem to resolve the problem

**Comment by lookye** [comment] 2021-04-24 14:30
There is no new information about it. Otherwise it would have been stated in the changelog ;)

**Comment by iSkyJIE** [comment] 2021-04-28 11:45
The problem is still not resolved, and there is still no bonus appearance equipment to receive

**Comment by Aeuko** [comment] 2021-04-29 03:41
Hope to support MHR soon

**Comment by Atthorpe** [comment] 2021-06-02 01:30
any luck ? 👀

**Comment by kainlt04** [comment] 2022-01-07 02:24
Hi, was anyone able to get the Per-game access ID from MHR?

**Comment by Glazelf** [comment] 2022-06-30 22:14
This issue persists with the Sunbreak expansion amiibos.

**Comment by dalokaVAl** [comment] 2022-07-04 12:55
After 3-4 hours of searching how to get the bonus from amiibos in mh rise, finally found this thread. I could never get the layered armoured from amiibos, also don’t work for Sunbreak expansion. Hope one day this issue will be fixed.

**Comment by TerraFlareKSFL** [comment] 2022-10-13 14:49
Is this issue still being looked at? Game doesnt want to grant bonuses from Sunbreak amiibos.

**Comment by JianYuhaha** [comment] 2023-02-26 03:38
23/2/26，In version 0.6.3, it is still not possible to receive the special equipment of Monster Hunter Rise

**Comment by lookye** [comment] 2023-05-05 16:43
This is solved with the latest release.

**Closed by lookye** 2023-05-05 16:43 UTC
