### ISSUE TITLE
EMUIIBO TESLA OVERLAY CRASH

### ISSUE THREAD

**Issue by Playnice11** [XorTroll/emuiibo#122] opened 2020-08-31 15:38 UTC
Guys help. 
I keep on crashing on emuiibo on tesla.

It is usually working before i updated my firmware. 

But after i updated my cfw to 10.1 atmos 0.14
My emuiibo overlay keeps on crashing

**Comment by lookye** [comment] 2020-08-31 15:40
This is already known and its being worked on.
Duplicate of #119

**Closed** 2020-08-31 15:56 UTC
