### ISSUE TITLE
All link amiibos have the same drops in botw. 

### ISSUE THREAD

**Issue by thb3** [XorTroll/emuiibo#30] opened 2019-07-05 10:07 UTC
Only drop fish as secondary and a chest with a random weapon

**Comment by thunder-17** [comment] 2019-07-07 20:05
Same issue

**Comment by thunder-17** [comment] 2019-07-07 20:31
I tried the Ocarina of Time one and it gives only fish, but the Wolf Link works fine, im going to try others

**Comment by lookye** [comment] 2019-07-07 20:34
#19 is nearly the same. Its a known issue.

**Comment by thunder-17** [comment] 2019-07-07 20:40
Guys, now my Zelda BOTW amiibos, works but when i want to use a different amiibo I need to close Zelda, change amiibo on AmiiSwap, then start the game

**Comment by thb3** [comment] 2019-07-08 13:32
All botw amiibos work fine, the only problem comes with the horse rider and archer link amiibos

**Comment by ctxngo** [comment] 2019-07-08 17:27
Let's be clear here since there seems to be a little confusion here. Toon Link (Super smash brothers and Windwaker Link) work properly. ALL OTHER LINKS do not work properly. 8 bit link, Ocarina of time link, Link rider, Link archer, smash Link, young Link, majora's mask Link, twilight princess Link, etc ARE NOT WORKING. When used they only give fish and a generic item (no unique item no horse etc).

**Comment by usuario593** [comment] 2019-07-23 16:03
Tambien tengo el mismo problema, ¿alguna solucion?

**Comment by tralyaeternus** [comment] 2019-09-25 16:46
I have the same problem with some amiibos using Breath of The Wild, even if I use emuGUIibo to generate them. 

You can see the expected items in the following web link:

[https://universozelda.com/2017/03/26/guia-definitiva-los-amiibo-breath-of-the-wild/](url)

The following ones are not working properly.

- Majora's mask Link (Link MM)
- Twilight princess Link (Link TP)
- Skyward Sword Link (Link SS)
- 8 bit link (30 TH Anniversary series: Link TLoZ)
- Ocarina of time link (30 TH Anniversary series: Link OoT)
- Toon Zelda (30 TH Anniversary series)
- Link rider
- Link archer
- Super Smash Bros Adult Link.
- Super Smash Bros Zelda

**Comment by Conando025** [comment] 2019-11-08 15:41
will they ever work?

**Comment by kawatzaki** [comment] 2019-11-19 03:57
Hi! 

I spent a looong time getting myself into this haha

I'll try to look into this issue, but I'm not familiar at all with the technology...

**Comment by Daniel2870** [comment] 2019-11-28 04:47
Any solution for this problem, the same thing happens to me

**Comment by kawatzaki** [comment] 2019-11-28 15:17
It'd be really useful if someone with Noexes could scan an NFC 215 coded Amiibo from the list of affected ones, and then do the same with Emuiibo. 

That's currently what I'm trying to do to figure out WTF is going on, but I've yet to have time to look into it...

**Comment by leo60228** [comment] 2019-12-09 14:58
Notably, the first four bytes of all affected Amiibo IDs are `01000000`. However, I don't see any way this would cause a bug...

**Comment by leo60228** [comment] 2019-12-09 14:58
Maybe some kind of hash collision? That seems unlikely, though.

**Comment by fau-fau** [comment] 2019-12-14 18:30
> Notably, the first four bytes of all affected Amiibo IDs are `01000000`. However, I don't see any way this would cause a bug...

i think the same too. maybe the "amiiboId" is wrong and the system regonizes this amiibo as a common one. 

> It'd be really useful if someone with Noexes could scan an NFC 215 coded Amiibo from the list of affected ones, and then do the same with Emuiibo.

i think we have a way to go

**Comment by Conando025** [comment] 2020-03-20 10:30
Are those Amiibos working in other games as they should? And I mean in a way that you can Identify it ist that Amiibo. I wanna know if it is BOTW specific or if those are just general problematic.

**Comment by Frankeroni** [comment] 2020-03-26 01:52
Is there a list of confirmed amiibos that work? I tried using the ones that aren't Link, and they still don't work :/

**Comment by Frankeroni** [comment] 2020-03-26 02:02
Is there an alternative way to get amiibos to work? Other than using this release? I don't reckon this issue will be fixed anytime soon...

**Comment by Frankeroni** [comment] 2020-03-26 02:10
I still have this issue after the latest release where the Changelog says: "Those problems with certain amiibos (mainly BOTW ones) have been fixed...".
The virtual amiibo creator still gives me random stuff.

**Comment by XorTroll** [comment] 2020-03-31 15:36
I've been testing BOTW amiibos (Majora's mask Link and more) and they do give the drops they should give, any special case I should try?

**Comment by XorTroll** [comment] 2020-04-09 17:57
BOTW should work for this next version, me and other testers have had no issues with special amiibo.
20 heart wolf link won't work, since the bin file should be decrypted and it's savedata should be extracted so that BOTW can detect it, but that's not supported by emuiibo.

**Closed by XorTroll** 2020-04-09 17:57 UTC

**Comment by grandiego77** [comment] 2021-09-10 22:51
I HAVE THE SOLUTION MY FRIENDS: AMIIBOS HAVE A CERTAIN % TO GIVE YOU THE PRICE YOU SEARCH, YOU HAVE TO SAVE THE GAME AND TRY THE AMIIBO, THEN YOU GET ANY PRICE, IF ITS NOT WHAT YOU LOOKING FOR, YOU RESET AND TRY AGAIN AND AGAIN AND AGAIN, I JUST GET THE FIERCE DEITY MASK

**Comment by Masamune3210** [comment] 2021-09-11 01:24
...please dont do that
